name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build trys
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sai hello
        run: echo hola
      - name: list schemas
        run: xcodebuild -list -workspace "CI M22.xcworkspace"
      - name: list proyects
        run: xcodebuild -list -project "CI M22.xcodeproj"
      - name: view files
        run: ls
      - name: view credentials
        run: echo ${{ secrets.DRIVE_CREDENTIALS }}
      - name: view folder
        run: echo ${{ secrets.DRIVE_FOLDER }}
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: "archive.zip"
          folderId: ${{ secrets.DRIVE_FOLDER }}
          name: "README.md" # optional string
          overwrite: "true" # optional boolean
